//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tBidding
    {
        public int fId { get; set; }
        [Display(Name ="工程名")]
        public string fName { get; set; }
        [Display(Name ="工程類型")]
        public string fCategory { get; set; }
        [Display(Name ="單位")]
        public string fUnit { get; set; }
        [Display(Name ="單位價格")]
        public Nullable<decimal> fUnitPrice { get; set; }
        [Display(Name ="總額")]
        public string fAmount { get; set; }
        [Display(Name ="投標公司")]
        public string fBidder { get; set; }
        [Display(Name ="經辦")]
        public string fChargeMan { get; set; }
        [Display(Name ="日期")]
        public Nullable<System.DateTime> fDate { get; set; }
        [Display(Name ="合約")]
        public string fContract { get; set; }
    }
}
