//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tMissionDetail
    {
        public int fId { get; set; }
        [Display(Name ="工程代碼")]
        public string fCode { get; set; }
        [Display(Name ="工程名")]
        public string fName { get; set; }
        [Display(Name ="原料")]
        public string fMaterial { get; set; }
        [Display(Name ="工頭")]
        public string fChargeMan { get; set; }
        [Display(Name ="人數")]
        public string fWorkers { get; set; }
        [Display(Name ="天氣")]
        public string fWeather { get; set; }
        [Display(Name ="日期")]
        public string fToday { get; set; }
        [Display(Name ="照片")]
        public string fPhoto { get; set; }
        [Display(Name ="備註")]
        public string fPS { get; set; }
    }
}
