//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMission
    {
        public int fId { get; set; }
        public string fName { get; set; }
        public string fProjectCode { get; set; }
        public string fStage { get; set; }
        public string fCode { get; set; }
        public string fEST_Time { get; set; }
        public string fSum_Time { get; set; }
        public string fReal_Time { get; set; }
        public double fComplete { get; set; }
        public string fChargeMan { get; set; }
        public string fConfirmer { get; set; }
        public string fPS { get; set; }
        public Nullable<decimal> fPayment { get; set; }
    
        public virtual tMission tMission1 { get; set; }
        public virtual tMission tMission2 { get; set; }
    }
}
