//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMyProjectEntities1 : DbContext
    {
        public dbMyProjectEntities1()
            : base("name=dbMyProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAnnouncement> tAnnouncement { get; set; }
        public virtual DbSet<tBidding> tBidding { get; set; }
        public virtual DbSet<tmail> tmail { get; set; }
        public virtual DbSet<tMessagBoard> tMessagBoard { get; set; }
        public virtual DbSet<tMessageConfirm> tMessageConfirm { get; set; }
        public virtual DbSet<tMission> tMission { get; set; }
        public virtual DbSet<tMission_SignOff> tMission_SignOff { get; set; }
        public virtual DbSet<tMissionDetail> tMissionDetail { get; set; }
        public virtual DbSet<tMissionDetail_Photos> tMissionDetail_Photos { get; set; }
        public virtual DbSet<tProject> tProject { get; set; }
        public virtual DbSet<tProject_Drawing> tProject_Drawing { get; set; }
        public virtual DbSet<tProject_HumanCost> tProject_HumanCost { get; set; }
        public virtual DbSet<tUser> tUser { get; set; }
    }
}
