//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tMessagBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMessagBoard()
        {
            this.tMessageConfirm = new HashSet<tMessageConfirm>();
        }

        public int fid { get; set; }
        [Display(Name = "主題")]
        public string ftitle { get; set; }
        [Display(Name = "ID")]
        public int fuser_id { get; set; }
        [Display(Name = "訊息")]
        public string fmessage { get; set; }
        [Display(Name = "時間")]
        public System.DateTime fdatetime { get; set; }
        [Display(Name ="部門")]
        public int fdepartment { get; set; }
        [Display(Name ="發佈者")]
        public int fauthority { get; set; }
    
        public virtual tUser tUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMessageConfirm> tMessageConfirm { get; set; }
    }
}
