//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tMission
    {
        public int fId { get; set; }        
        [Display(Name ="工程名")]
        public string fName { get; set; }
        [Display(Name ="專案代碼")]
        public string fProjectCode { get; set; }
        [Display(Name ="階段")]
        public string fStage { get; set; }
        [Display(Name ="工程代碼")]
        public string fCode { get; set; }
        [Display(Name ="開工日期")]
        public string fEST_Time { get; set; }
        [Display(Name ="工程日數")]
        public string fSum_Time { get; set; }
        [Display(Name ="完工日期")]
        public string fReal_Time { get; set; }
        public Nullable<double> fComplete { get; set; }
        [Display(Name ="負責人")]
        public string fChargeMan { get; set; }
        [Display(Name ="備註")]
        public string fPS { get; set; }
        [Display(Name ="工程款")]
        public Nullable<decimal> fPayment { get; set; }
        [Display(Name ="電話")]
        public string fPhone { get; set; }
    
        public virtual tMission tMission1 { get; set; }
        public virtual tMission tMission2 { get; set; }
    }
    
}
