//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tProject_HumanCost
    {
        public int fId { get; set; }
        [Display(Name ="專案代碼")]
        public string fProjectCode { get; set; }
        [Display(Name ="職稱")]
        public string fLevel { get; set; }
        [Display(Name ="薪資")]
        public Nullable<decimal> fSalary { get; set; }
        [Display(Name ="人數")]
        public int fNumberOfPeople { get; set; }
        [Display(Name ="起雇日")]
        public System.DateTime fStartDate { get; set; }
        [Display(Name ="結束日")]
        public System.DateTime fEndDate { get; set; }
    }
}
