//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tAnnouncement
    {
        public int fId { get; set; }
        [Display(Name ="發佈者")]
        public string fPoster { get; set; }
        [Display(Name ="類型")]
        public string fType { get; set; }
        [Display(Name ="收件者")]
        public string fGetter { get; set; }
        [Display(Name ="訊息")]
        public string fMessage { get; set; }
        [Display(Name ="時間")]
        public string fTime { get; set; }
        [Display(Name ="主題")]
        public string fTitle { get; set; }
    }
}
