//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tmail
    {
        public int fid { get; set; }
        [Display(Name ="主題")]
        public string ftitle { get; set; }
        [Display(Name ="日期")]
        public Nullable<System.DateTime> fdate { get; set; }
        [Display(Name ="ID")]
        public int fsendid { get; set; }
        [Display(Name ="收件者")]
        public int frecieveid { get; set; }
        [Display(Name ="訊息")]
        public string fmessage { get; set; }
        [Display(Name ="回復ID")]
        public Nullable<int> replymaiid { get; set; }
       
        public bool isreplied { get; set; }
        public bool fisreaded { get; set; }
        public bool fsenddelete { get; set; }
        public bool freceievedelete { get; set; }
    
        public virtual tUser tUser { get; set; }
        public virtual tUser tUser1 { get; set; }
    }
}
