//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUser()
        {
            this.tmail = new HashSet<tmail>();
            this.tmail1 = new HashSet<tmail>();
            this.tMessagBoard = new HashSet<tMessagBoard>();
            this.tMessageConfirm = new HashSet<tMessageConfirm>();
        }
    
        public int fId { get; set; }
        public string fAccount { get; set; }
        public string fPassword { get; set; }
        public string fName { get; set; }
        public string fStatus { get; set; }
        public System.DateTime fArrivingDate { get; set; }
        public Nullable<System.DateTime> fLeavingDate { get; set; }
        public string fEmail { get; set; }
        public string fPhone { get; set; }
        public string fAddress { get; set; }
        public string fEmployeeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmail> tmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmail> tmail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMessagBoard> tMessagBoard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMessageConfirm> tMessageConfirm { get; set; }
    }
}
