//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmail
    {
        public int fid { get; set; }
        public string ftitle { get; set; }
        public Nullable<System.DateTime> fdate { get; set; }
        public int fsendid { get; set; }
        public int frecieveid { get; set; }
        public string fmessage { get; set; }
        public Nullable<int> replymaiid { get; set; }
        public bool isreplied { get; set; }
        public bool fisreaded { get; set; }
        public bool fsenddelete { get; set; }
        public bool freceievedelete { get; set; }
    
        public virtual tUser tUser { get; set; }
        public virtual tUser tUser1 { get; set; }
    }
}
