//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMission_SignOff
    {
        public int fId { get; set; }
        public string fMissionCode { get; set; }
        public string fContract { get; set; }
        public Nullable<decimal> fMoney { get; set; }
        public string fChargeMan { get; set; }
        public string fManager { get; set; }
        public string fStatus { get; set; }
        public string fDetails { get; set; }
        public Nullable<System.DateTime> fConfirmDate { get; set; }
    }
}
