//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProject
    {
        public int fId { get; set; }
        public string fName { get; set; }
        public System.DateTime fEST_StartDate { get; set; }
        public System.DateTime fEST_EndDate { get; set; }
        public Nullable<System.DateTime> fReal_StartDate { get; set; }
        public Nullable<System.DateTime> fReal_EndDate { get; set; }
        public string fChargeMan { get; set; }
        public string fLocation { get; set; }
        public string fBoss { get; set; }
        public Nullable<decimal> fMoney { get; set; }
        public string fDetail { get; set; }
        public string fCode { get; set; }
    }
}
