//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProject_HumanCost
    {
        public int fId { get; set; }
        public string fProjectCode { get; set; }
        public string fLevel { get; set; }
        public Nullable<decimal> fSalary { get; set; }
        public int fNumberOfPeople { get; set; }
        public System.DateTime fStartDate { get; set; }
        public System.DateTime fEndDate { get; set; }
    }
}
