//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
        public ProjectEntities()
            : base("name=ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mydrink> Mydrinks { get; set; }
        public virtual DbSet<Mymeat> Mymeats { get; set; }
        public virtual DbSet<Mymember> Mymembers { get; set; }
        public virtual DbSet<Mypicture> Mypictures { get; set; }
        public virtual DbSet<Myvegetable> Myvegetables { get; set; }
        public virtual DbSet<Myexercise> Myexercises { get; set; }
    }
}
